APP__HttpServer_Addr: ""
APP__HttpServer_Port: 80
APP__MysqlOnline_DbName: ""
APP__MysqlOnline_Extra: charset=utf8mb4&parseTime=True
APP__MysqlOnline_Host: 127.0.0.1
APP__MysqlOnline_Password: ""
APP__MysqlOnline_Port: 3306
APP__MysqlOnline_User: ""
