
### Create Post
POST http://127.0.0.1:8088/v0/blog/post
Content-Type: application/json

{
    "title":"时间怎么搞？",
    "content":"sql 语句里面居然可以使用 sql 函数。 now() "
}



### Get Post By ID
GET http://127.0.0.1:8088/v0/blog/post/3